### ISSUE TITLE
Does not compile on rust 1.42.0 

### ISSUE THREAD

**Issue by zachatttack** [cwoodall/pcan-basic-sys#4]
```
~$>cargo --version
cargo 1.42.0 (86334295e 2020-01-31)
```
```
error[E0423]: expected function, tuple struct or tuple variant, found struct `ast::Name`
   --> C:\Users\zthomas\.cargo\registry\src\github.com-1ecc6299db9ec823\syntex_syntax-0.58.1\src\symbol.rs:146:27
    |
146 |                       name: ast::Name($index),
    |                             ^^^^^^^^^
...
165 | / declare_keywords! {
166 | |     // Invalid identifier
167 | |     (0,  Invalid,        "")
168 | |
...   |
231 | |     (56, CrateRoot, "{{root}}")
232 | | }
    | |_- in this macro invocation

error: aborting due to previous error
```
The crate `bindgen 0.24.0` depends on crate `syntex_syntax 0.58.1` 

Is it possible to update to the latest version of bindgen which does not depend on syntex_syntax?

**Comment by cwoodall** [comment]
Hello @zachatttack  I have not worked on this in a while and may not touch it again anytime soon (sadly).

If you want to try to chase it down and fix it I will integrate your changes here :)

**Comment by cwoodall** [comment]
@zachatttack saw your PR just now, merged it in after getting a confirmation of it working for others.

I actually have some use for this again now.

I would like to wrap a generic can library that takes all can sources and allows you to select which to use (or based on platform)... This was supposed to be a start to that
